### ISSUE TITLE
웹 - 개발경험 프로젝트 수업에 대해 회고한다.

### ISSUE THREAD

**Issue by javajigi** [NHNNEXT/2016-3-MOJITO_WEB#10]
다음 주 수업 시간에 데모와 더불어 회고도 진행할께요.
수업 시간에 회고를 바로 진행하면 딱히 생각나는 것도 없기 때문에 미리 온라인으로 회고를 먼저 진행할께요.

이 이슈의 댓글로 다음 내용을 정리해 주세요.
수업, 프로젝트, 교수, 팀 동료 등 모든 영역에 대한 좋은 점, 아쉬운 점, 개선하고나 시도하고 싶은 것 3가지로 나눠 정리해 주면 됩니다.

@mixed 교수님도 하고 싶은 이야기 있으시면 남겨주세요.

### 개선하고나 시도하고 싶은 것

**Comment by bbq923** [comment]
### 좋은 점
- 자신의 학습 속도에 맞춰 진행할 수 있는 동영상 반복 주기 강의
- 교수대 학생비율이 1:1이라는 환상적인 환경에서 자유롭게 질문할 수 있음
- 학생 수가 적어 이슈가 발생해도 교수님이 맨투맨으로 붙어 바로 해결할 수 있어 강의 진행이 원활

### 아쉬운 점
- 학생 수가 적어 장점도 있지만 반대로 여러 팀이 나올 수 없어 다른 팀과 진행 상황을 경쟁할 수 없어
  자칫 루즈해지기 쉬움

### 개선하고나 시도하고 싶은 것
- 현재 방식이 잘 맞는 것 같습니다.

**Comment by javajigi** [comment]
### 좋은 점
- 각 반복주기에 맞춰 꾸준히 학습하고 있는 점
- 교수와 학생 간에 깊이 있는 질답과 소통을 할 수 있는 점

### 아쉬운 점
- 너무 큰 단위로 커밋을 하거나 한번에 너무 깊이 있는 부분까지 개발하려는 점
- 구현 코드가 많지 않아 피드백할 부분이 많지 않은 점
- 또 한명의 팀원이라 할 수 있는 @JaeYeopHan 과 소통하기 힘든 점

### 개선하거나 시도하고 싶은 것
- 더 많은 질문과 구현 코드로 교수들을 더 괴롭혔으면 좋겠음.
- @bbq923 와 @wkddngus5 가 더 자주 짝 프로그래밍하는 모습을 보았으면 좋겠음.
- 현재 어떤 작업을 하고 있는지에 대한 가시화할 수 있는 방법을 찾았으면 좋겠음.

**Comment by jbee37142** [comment]
### 좋은 점
- 수강신청을 하지 않아도 동영상 강의를 통해서 수업의 60%정도는 수강할 수 있다. 정말 감격스러운 부분이다. 동영상 강의의 또 다른 장점은 강의의 완급을 수강생이 조절할 수 있는데 있다. 동영상 강의에 대한 예찬은 여기까지. 
- 팀 프로젝트에서만 경험할 수 있는 Git을 열심히 잘 배우고 있는 것 같아서 좋다. 
- Spring 프레임워크로 시작하지 않고 Spring boot로 시작한 것은 신의 한수였던 것 같다. 하지만 이 부분은 양날의 검이라고 생각되기도 한다. 
- 코드 리뷰를 받으면 동기 부여가 생긴다. 경쟁 팀이 없어서 루즈해질 수 있다는 김대훈 군의 말에는 동의할 수 없다.(ㅋㅋㅋ) 내가 생각했을 때 김대훈 군은 경쟁팀이 없어도 루즈해졌을 것 같다. 
- 그냥 좋다. 

### 아쉬운 점
- 분명 진행사항을 현재 진행상황을 공유할 수 있는 '구글 시트'가 마련되어 있음에도 불구하고 김대훈 군과 장우현 군은 그 시트에 들어오지 않는다. 매번 카톡으로 의사소통을 해도, 망각할 수 있는 한계가 존재한다. 이 문제로 내가 구현하기로 했던 부분을 장우현 군이 구현하다가 말았던 경우도 있었다. 또 Slack을 Github과 연동하여 사용하고 있는데 아무도 Slack을 사용하지 않는다(ㅋㅋ). 일상 대화를 나눌 수 있는 카톡에 비해 프로젝트 관련 대화만 하기로 한 Slack에서 현재 진행상황을 공유할 수 있을 텐데 아쉽다. (데스크탑 애플리케이션 Slack 이 있어서 구글 시트보다 접근성이 좋다고 생각하여 이번 프로젝트에 사용했지만 그 활용성이 아쉽다!) 
- 수업에 들어가서 함께 소통할 수 없는 것은 정말 아쉽다. 
- 3학기가 4과목밖에(실제로는 5과목이지만) 수강하고 있지 않는데 상당히 버겁다. 네트워크, 자료구조 알고리즘2, DB basic 모두 만만치 않다. 그래서 프로젝트에 할애되는 시간이 자연스럽게 적어진다. (기초과목도 열심히 공부하고 있습니다. 너무 걱정마세요 교수님ㅋㅋ) 
- 내 스스로가 너무 html/css에 집착하고 있는 것 같다. 그렇다고 디자인이 훌륭한 것도 아니다. 

### 개선하거나 시도하고 싶은 것
- 분명 프로젝트가 온전하게 마무리 되지 않을 것 같으니 프로젝트를 마치고 교수님과 팀원들과 함께 '스타족발'에서 포스트모뎀을 진행했으면 좋겠다.
- wiki 탭을 활용하여 새롭게 알게 된 내용이나, 자신이 코드를 구현하는데 있어서 힘들게 해결한 부분을 공유하면 어떨까 생각해보았다. 웹 UI Basic 시간에는 Issue 탭을 활용하여 유용한 정보를 활용하곤 했다. 딱히 많은 정보가 공유됬던 것은 아니지만, 좋을 것 같다. 
- 다음 학기에 있을 휴먼 디자인 프로젝트에서는 스터디를 진행하면서 프로젝트를 진행하면 어떨가 하는 생각도 해봤다. 

_두서없이 이것 저것 적어봤습니다._
