### ISSUE TITLE
FE이것이 궁금하다.

### ISSUE THREAD

**Issue by mixed** [NHNNEXT/2016-3-MOJITO_WEB#34]
궁금한 점은 댓글로
@bbq923 @wkddngus5

**Comment by wkddngus5** [comment]
레이어 팝업 만드는 법 궁금합니다~

**Comment by bbq923** [comment]
스토리보드를 처음 받은 상태에서 어떻게 시작해야 할지 막막합니다. template을 사용하지 않고 백지 상태에서 시작할 때
어떻게 손을 대야 할 지... 스토리 보드에서 출발해서 기본적인 마크업을 구성하는 과정을 볼 수 있으면 좋을 것 같습니다. 반복주기에서는 FE 부분을 미리 준비된 템플릿으로 채우고 넘어갔는데 아무것도 없는 상태에서 시작하는 과정을 보고 싶습니다.
세부적으로는 클래스 명을 정하는 규칙이라든지 어떤 경우에 아이디, 클래스를 사용하는지, 이것들을 남발하지 않기 위해
어떻게 구조화 시키는지. 한 페이지의 부분 부분들에 대해 div는 어떨 때 감싸고 어떨 때 감싸지 않는 지 등 이런 기본적인
부분에서 적절한 선이 어느 정도인지 감이 안잡힙니다.. WEB/UI Basic에서 이런 부분은 적어도 익히도 들어왔어야 
했는데 죄송합니다 ㅠㅠ

***그 외 개별적인 질문들*** 

* div를 사용하는 대신 nav나 article 같은 태그를 쓰는 것은 그렇게 하는 것이 의미(semantic)가 있기 때문인가요? 
div에 클래스나 아이디를 사용하는 것과 태그를 구분해서 사용하는 것은 어떤 차이점이 있나요?

* 크로스 브라우저 이슈를 해결할 때 사용하는 툴 같은 게 있나요? 테스트 할 때 일일이 해당 브라우저에서 어떻게 표시되는 지 확인하는 식으로 진행되나요? java의 jUnit 테스트 케이스를 실행할 때처럼 모든 브라우저에서 올바르게 작동되었다는 것을 정량적으로 검사하는 방법은 없나요?

* AJAX로 받아온 응답을 화면에 반영해 줄 때, 한 번 로딩한 페이지에 대한 변경사항은 누가 detect 하나요? 브라우저가 한다면, 어떻게 하나요? 지금 저희의 수준에서 이해하는 건 힘들겠지만 수박 겉핥기 식으로라도 그 과정을 알고 싶습니다. 

* 자바스크립트를 사용하지 않고 순수한 css로 구현하면 성능상에 얼마나 차이가 날까요? (예를 들어 프로그레스 바를 구현한다고 했을 때...) 현재의 브라우저에서도 여전히 css만으로 구현하는 것이 가치가 있는 작업인가요?

* 교수님이 생각하시는 semantic HTML 이란?

**Comment by mixed** [comment]
- [기본적인 CSS 설계](http://wit.nts-corp.com/2015/04/16/3538)
